version: 2
updates:
  - package-ecosystem: "npm"
    directory: "application/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
  - package-ecosystem: "npm"
    directory: "web-client/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
