version: '3.9'
services:
  application:
    container_name: twttr-backend
    build: application/
    ports:
    - '3000:3000'
  client:
    container_name: twttr-frontend
    build: web-client/
    ports:
    - '4000:4000'
  database:
    container_name: twttr-postgres
    image: postgres:12-alpine
    volumes:
      - ../log:/root/log:cached
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PSQL_HISTFILE=/root/log/.psql_history
      - POSTGRES_DB=postgres
    ports:
    - '5556:5432'
  grafana:
    image: grafana/grafana:latest
    container_name: twttr-grafana
    restart: unless-stopped
    user: "104"
    ports:
    - '3030:3000'
  cache:
    image: redis:6.2.5-alpine
    container_name: twttr-cache
    expose:
      - 6379
    ports:
      - '6379:6379'
  monitoring:
    image: prom/prometheus:latest
    container_name: twttr-monitoring
    ports:
      - '9090:9090'
