# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js application

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
#    paths:
#      - 'application/**'

env:
  CI: true
  TYPEORM_CONNECTION: postgres
  TYPEORM_HOST: localhost
  TYPEORM_USERNAME: postgres
  TYPEORM_PASSWORD: postgres
  TYPEORM_DATABASE: postgres
  TYPEORM_PORT: 5432
  TYPEORM_SYNCHRONIZE: true
  TYPEORM_LOGGING: true
  TYPEORM_MIGRATIONS_DIR: src/db/migration/
  TYPEORM_MIGRATIONS: src/db/migration/**/*.ts
  TYPEORM_ENTITIES: src/db/entity/**/*.ts

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ["5432:5432"]
    defaults:
      run:
        working-directory: ./application

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1

      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Run db migrations
        run: npm run db:migrate
      - name: Run linters
        run: npm run linter:js
      - name: Run tests
        run: npm run test:coverage
